import type { FastifyRequest, FastifyReply } from 'fastify';
import { writeFileSync, mkdtempSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { randomUUID } from 'crypto';
import { FEED_IMAGE_EXTENSIONS, FEED_IMAGE_MAX_BYTES } from '../../../shared/mcp.js';
import { SessionFeeder } from './feedImage.js';

/** Session IDs are generated by `randomUUID` (SessionManager.create) — hex
 * digits and hyphens only. Rejecting anything else at the route boundary is
 * what stops a spoofed `../foo` from turning
 * `join(tmpdir(), 'cchub-paste-'+sid+'-')` into a path outside tmpdir. `\`
 * on Windows and `/` everywhere are the traversal shapes we most need to
 * catch; be strict by default and only accept the alphabet a UUID actually
 * uses (plus underscore, in case a caller stitches together a test id). */
const SESSION_ID_RE = /^[A-Za-z0-9_-]{1,64}$/;

/** Maps an inbound MIME type to the on-disk extension feed_image already
 * whitelists. Anything outside this map is rejected before we touch the disk. */
const MIME_TO_EXT: Record<string, (typeof FEED_IMAGE_EXTENSIONS)[number]> = {
  'image/png': 'png',
  'image/jpeg': 'jpeg',
  'image/jpg': 'jpeg', // browsers sometimes ship this non-standard label
  'image/gif': 'gif',
  'image/webp': 'webp',
};

/** Build the Fastify handler for `POST /paste-image/:sessionId`. The browser
 * intercepts a `paste` event whose clipboardData carries an image blob, posts
 * the bytes here, and we land them on disk in a session-scoped tmp directory
 * before handing the path to the same feeder the MCP `feed_image` tool uses.
 *
 * Bytes go to `os.tmpdir()/cchub-paste-<sessionId>/<uuid>.<ext>`. The dir
 * survives the session's lifetime so a clicked `[Image #N]` chip can resolve
 * back to disk; cleanup happens incidentally with the OS tmp sweep. */
export function makePasteImageRouteHandler(feeder: SessionFeeder) {
  // Lazy per-session dir so we don't litter tmp for sessions that never paste.
  const sessionDirs = new Map<string, string>();
  function dirFor(sessionId: string): string {
    let dir = sessionDirs.get(sessionId);
    if (!dir) {
      dir = mkdtempSync(join(tmpdir(), `cchub-paste-${sessionId}-`));
      sessionDirs.set(sessionId, dir);
    }
    return dir;
  }

  return async function handle(
    request: FastifyRequest<{ Params: { sessionId: string } }>,
    reply: FastifyReply,
  ): Promise<FastifyReply> {
    const { sessionId } = request.params;
    if (!SESSION_ID_RE.test(sessionId)) {
      return reply.code(400).send({ error: 'invalid session id' });
    }
    const mime = (request.headers['content-type'] || '').split(';')[0]!.trim().toLowerCase();
    const ext = MIME_TO_EXT[mime];
    if (!ext) {
      return reply.code(415).send({ error: `unsupported image type: ${mime}` });
    }
    // The content-type parser we register hands us a Buffer for image/*.
    const body = request.body;
    if (!Buffer.isBuffer(body) || body.length === 0) {
      return reply.code(400).send({ error: 'empty body' });
    }
    if (body.length > FEED_IMAGE_MAX_BYTES) {
      return reply.code(413).send({ error: `image too large: ${body.length} bytes (max ${FEED_IMAGE_MAX_BYTES})` });
    }
    const imagePath = join(dirFor(sessionId), `${randomUUID()}.${ext}`);
    try {
      writeFileSync(imagePath, body);
    } catch (err) {
      return reply.code(500).send({ error: `failed to write image: ${err instanceof Error ? err.message : String(err)}` });
    }
    try {
      // The user pressed Ctrl+V — leave the CR for them so they can pair the
      // image with a typed prompt before submitting. MCP feed_image is the only
      // path that auto-submits (that call is triggered by the agent, which can
      // never itself press Enter).
      await feeder.feed(sessionId, imagePath, { autoSubmit: false });
    } catch (err) {
      return reply.code(400).send({ error: err instanceof Error ? err.message : String(err) });
    }
    return reply.code(204).send();
  };
}
